// <auto-generated />
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220527225125_AddStatsView")]
    partial class AddStatsView
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("Domain.Match", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ground")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LocalScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Visitor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VisitorScore")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Matches", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "Canada",
                            Local = "Canada",
                            LocalScore = 2,
                            Visitor = "Mexico",
                            VisitorScore = 1
                        },
                        new
                        {
                            ID = 2,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "Canada",
                            Local = "Canada",
                            LocalScore = 2,
                            Visitor = "United States",
                            VisitorScore = 0
                        },
                        new
                        {
                            ID = 3,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "Canada",
                            Local = "Canada",
                            LocalScore = 1,
                            Visitor = "Costa Rica",
                            VisitorScore = 0
                        },
                        new
                        {
                            ID = 4,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "Canada",
                            Local = "Canada",
                            LocalScore = 4,
                            Visitor = "Panama",
                            VisitorScore = 1
                        },
                        new
                        {
                            ID = 5,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "Canada",
                            Local = "Canada",
                            LocalScore = 4,
                            Visitor = "Jamaica",
                            VisitorScore = 0
                        },
                        new
                        {
                            ID = 6,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "Canada",
                            Local = "Canada",
                            LocalScore = 3,
                            Visitor = "El Salvador",
                            VisitorScore = 0
                        },
                        new
                        {
                            ID = 7,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "Canada",
                            Local = "Canada",
                            LocalScore = 1,
                            Visitor = "Honduras",
                            VisitorScore = 1
                        },
                        new
                        {
                            ID = 8,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "Mexico",
                            Local = "Mexico",
                            LocalScore = 1,
                            Visitor = "Canada",
                            VisitorScore = 1
                        },
                        new
                        {
                            ID = 9,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "Mexico",
                            Local = "Mexico",
                            LocalScore = 0,
                            Visitor = "United States",
                            VisitorScore = 0
                        },
                        new
                        {
                            ID = 10,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "Mexico",
                            Local = "Mexico",
                            LocalScore = 0,
                            Visitor = "Costa Rica",
                            VisitorScore = 0
                        },
                        new
                        {
                            ID = 11,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "Mexico",
                            Local = "Mexico",
                            LocalScore = 1,
                            Visitor = "Panama",
                            VisitorScore = 0
                        },
                        new
                        {
                            ID = 12,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "Mexico",
                            Local = "Mexico",
                            LocalScore = 2,
                            Visitor = "Jamaica",
                            VisitorScore = 1
                        },
                        new
                        {
                            ID = 13,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "Mexico",
                            Local = "Mexico",
                            LocalScore = 2,
                            Visitor = "El Salvador",
                            VisitorScore = 0
                        },
                        new
                        {
                            ID = 14,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "Mexico",
                            Local = "Mexico",
                            LocalScore = 3,
                            Visitor = "Honduras",
                            VisitorScore = 0
                        },
                        new
                        {
                            ID = 15,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "United States",
                            Local = "United States",
                            LocalScore = 1,
                            Visitor = "Canada",
                            VisitorScore = 1
                        },
                        new
                        {
                            ID = 16,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "United States",
                            Local = "United States",
                            LocalScore = 2,
                            Visitor = "Mexico",
                            VisitorScore = 0
                        },
                        new
                        {
                            ID = 17,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "United States",
                            Local = "United States",
                            LocalScore = 2,
                            Visitor = "Costa Rica",
                            VisitorScore = 1
                        },
                        new
                        {
                            ID = 18,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "United States",
                            Local = "United States",
                            LocalScore = 5,
                            Visitor = "Panama",
                            VisitorScore = 1
                        },
                        new
                        {
                            ID = 19,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "United States",
                            Local = "United States",
                            LocalScore = 2,
                            Visitor = "Jamaica",
                            VisitorScore = 0
                        },
                        new
                        {
                            ID = 20,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "United States",
                            Local = "United States",
                            LocalScore = 1,
                            Visitor = "El Salvador",
                            VisitorScore = 0
                        },
                        new
                        {
                            ID = 21,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "United States",
                            Local = "United States",
                            LocalScore = 3,
                            Visitor = "Honduras",
                            VisitorScore = 0
                        },
                        new
                        {
                            ID = 22,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "Costa Rica",
                            Local = "Costa Rica",
                            LocalScore = 1,
                            Visitor = "Canada",
                            VisitorScore = 0
                        },
                        new
                        {
                            ID = 23,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "Costa Rica",
                            Local = "Costa Rica",
                            LocalScore = 0,
                            Visitor = "Mexico",
                            VisitorScore = 1
                        },
                        new
                        {
                            ID = 24,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "Costa Rica",
                            Local = "Costa Rica",
                            LocalScore = 2,
                            Visitor = "United States",
                            VisitorScore = 0
                        },
                        new
                        {
                            ID = 25,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "Costa Rica",
                            Local = "Costa Rica",
                            LocalScore = 1,
                            Visitor = "Panama",
                            VisitorScore = 0
                        },
                        new
                        {
                            ID = 26,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "Costa Rica",
                            Local = "Costa Rica",
                            LocalScore = 1,
                            Visitor = "Jamaica",
                            VisitorScore = 1
                        },
                        new
                        {
                            ID = 27,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "Costa Rica",
                            Local = "Costa Rica",
                            LocalScore = 2,
                            Visitor = "El Salvador",
                            VisitorScore = 1
                        },
                        new
                        {
                            ID = 28,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "Costa Rica",
                            Local = "Costa Rica",
                            LocalScore = 2,
                            Visitor = "Honduras",
                            VisitorScore = 1
                        },
                        new
                        {
                            ID = 29,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "Panama",
                            Local = "Panama",
                            LocalScore = 1,
                            Visitor = "Canada",
                            VisitorScore = 0
                        },
                        new
                        {
                            ID = 30,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "Panama",
                            Local = "Panama",
                            LocalScore = 1,
                            Visitor = "Mexico",
                            VisitorScore = 1
                        },
                        new
                        {
                            ID = 31,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "Panama",
                            Local = "Panama",
                            LocalScore = 1,
                            Visitor = "United States",
                            VisitorScore = 0
                        },
                        new
                        {
                            ID = 32,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "Panama",
                            Local = "Panama",
                            LocalScore = 0,
                            Visitor = "Costa Rica",
                            VisitorScore = 0
                        },
                        new
                        {
                            ID = 33,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "Panama",
                            Local = "Panama",
                            LocalScore = 3,
                            Visitor = "Jamaica",
                            VisitorScore = 2
                        },
                        new
                        {
                            ID = 34,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "Panama",
                            Local = "Panama",
                            LocalScore = 2,
                            Visitor = "El Salvador",
                            VisitorScore = 1
                        },
                        new
                        {
                            ID = 35,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "Panama",
                            Local = "Panama",
                            LocalScore = 1,
                            Visitor = "Honduras",
                            VisitorScore = 1
                        },
                        new
                        {
                            ID = 36,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "Jamaica",
                            Local = "Jamaica",
                            LocalScore = 0,
                            Visitor = "Canada",
                            VisitorScore = 0
                        },
                        new
                        {
                            ID = 37,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "Jamaica",
                            Local = "Jamaica",
                            LocalScore = 1,
                            Visitor = "Mexico",
                            VisitorScore = 2
                        },
                        new
                        {
                            ID = 38,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "Jamaica",
                            Local = "Jamaica",
                            LocalScore = 1,
                            Visitor = "United States",
                            VisitorScore = 1
                        },
                        new
                        {
                            ID = 39,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "Jamaica",
                            Local = "Jamaica",
                            LocalScore = 0,
                            Visitor = "Costa Rica",
                            VisitorScore = 1
                        },
                        new
                        {
                            ID = 40,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "Jamaica",
                            Local = "Jamaica",
                            LocalScore = 0,
                            Visitor = "Panama",
                            VisitorScore = 3
                        },
                        new
                        {
                            ID = 41,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "Jamaica",
                            Local = "Jamaica",
                            LocalScore = 1,
                            Visitor = "El Salvador",
                            VisitorScore = 1
                        },
                        new
                        {
                            ID = 42,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "Jamaica",
                            Local = "Jamaica",
                            LocalScore = 2,
                            Visitor = "Honduras",
                            VisitorScore = 1
                        },
                        new
                        {
                            ID = 43,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "El Salvador",
                            Local = "El Salvador",
                            LocalScore = 0,
                            Visitor = "Canada",
                            VisitorScore = 2
                        },
                        new
                        {
                            ID = 44,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "El Salvador",
                            Local = "El Salvador",
                            LocalScore = 0,
                            Visitor = "Mexico",
                            VisitorScore = 2
                        },
                        new
                        {
                            ID = 45,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "El Salvador",
                            Local = "El Salvador",
                            LocalScore = 0,
                            Visitor = "United States",
                            VisitorScore = 0
                        },
                        new
                        {
                            ID = 46,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "El Salvador",
                            Local = "El Salvador",
                            LocalScore = 1,
                            Visitor = "Costa Rica",
                            VisitorScore = 2
                        },
                        new
                        {
                            ID = 47,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "El Salvador",
                            Local = "El Salvador",
                            LocalScore = 1,
                            Visitor = "Panama",
                            VisitorScore = 0
                        },
                        new
                        {
                            ID = 48,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "El Salvador",
                            Local = "El Salvador",
                            LocalScore = 1,
                            Visitor = "Jamaica",
                            VisitorScore = 1
                        },
                        new
                        {
                            ID = 49,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "El Salvador",
                            Local = "El Salvador",
                            LocalScore = 0,
                            Visitor = "Honduras",
                            VisitorScore = 0
                        },
                        new
                        {
                            ID = 50,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "Honduras",
                            Local = "Honduras",
                            LocalScore = 0,
                            Visitor = "Canada",
                            VisitorScore = 2
                        },
                        new
                        {
                            ID = 51,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "Honduras",
                            Local = "Honduras",
                            LocalScore = 0,
                            Visitor = "Mexico",
                            VisitorScore = 1
                        },
                        new
                        {
                            ID = 52,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "Honduras",
                            Local = "Honduras",
                            LocalScore = 1,
                            Visitor = "United States",
                            VisitorScore = 4
                        },
                        new
                        {
                            ID = 53,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "Honduras",
                            Local = "Honduras",
                            LocalScore = 0,
                            Visitor = "Costa Rica",
                            VisitorScore = 0
                        },
                        new
                        {
                            ID = 54,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "Honduras",
                            Local = "Honduras",
                            LocalScore = 2,
                            Visitor = "Panama",
                            VisitorScore = 3
                        },
                        new
                        {
                            ID = 55,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "Honduras",
                            Local = "Honduras",
                            LocalScore = 0,
                            Visitor = "Jamaica",
                            VisitorScore = 2
                        },
                        new
                        {
                            ID = 56,
                            Date = new DateTime(2022, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ground = "Honduras",
                            Local = "Honduras",
                            LocalScore = 0,
                            Visitor = "El Salvador",
                            VisitorScore = 2
                        });
                });

            modelBuilder.Entity("Domain.TeamStats", b =>
                {
                    b.Property<int>("Draws")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Games")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoalsAgainst")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoalsDiff")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoalsInFavor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Losts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Wins")
                        .HasColumnType("INTEGER");

                    b.ToView("vmStats");
                });
#pragma warning restore 612, 618
        }
    }
}
